version: "2"
run:
  concurrency: 4
  issues-exit-code: 1
  tests: false
linters:
  enable:
    - revive
    - gocritic
    - gocyclo
    - lll
    - misspell
    - nakedret
    - nilerr
    - staticcheck
    - whitespace
  disable:
    - errcheck
  settings:
    staticcheck:
      checks:
        - all
        - -QF1008
        - -QF1001
        - -ST1003
        - -ST1011
    revive:
      severity: error
      enable-all-rules: false
      rules:
        - name: package-comments
          severity: error
          disabled: false
          exclude: []
        - name: exported
          severity: error
          disabled: false
          exclude: []
          arguments:
            - "check-private-receivers"
            - "disableStutteringCheck"
            - "disable-checks-on-constants"
            - "disable-checks-on-types"
            - "disable-checks-on-variables"

    lll:
      # Max line length, lines longer will be reported.
      # '\t' is counted as 1 character by default, and can be changed with the tab-width option.
      # Default: 120.
      line-length: 120
      # Tab width in spaces.
      # Default: 1
      tab-width: 1

issues:
  uniq-by-line: false
  # Show only new issues: if there are unstaged changes or untracked files,
  # only those changes are analyzed, else only changes in HEAD~ are analyzed.
  # It's a super-useful option for integration of golangci-lint into existing large codebase.
  # It's not practical to fix all existing issues at the moment of integration:
  # much better don't allow issues in new code.
  #
  # Default: false
  new: false
  # REMOVED: new-from-merge-base and new-from-rev were hiding all issues
  # To only check new code, uncomment ONE of these:
  # new-from-rev: origin/master  # Check only code different from origin/master
  # new: true                    # Check only unstaged/untracked files or HEAD~

  # Fix found issues (if it's supported by the linter).
  # Default: false
  fix: true

formatters:
  enable:
    - gofmt
    - goimports
    - golines
    - gofumpt
  settings:
    gofmt:
      # Simplify code: gofmt with `-s` option.
      # Default: true
      simplify: false
      # Apply the rewrite rules to the source before reformatting.
      # https://pkg.go.dev/cmd/gofmt
      # Default: []
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
        - pattern: 'a[b:len(a)]'
          replacement: 'a[b:]'
    goimports:
      local-prefixes:
        - github.com/TencentBlueKing/blueking-micro-apigateway/apiserver
    gofumpt:
      # Module path which contains the source code being formatted.
      # Default: ""
      module-path: github.com/TencentBlueKing/blueking-micro-apigateway/apiserver
      # Choose whether to use the extra rules.
      # Default: false
      extra-rules: true
    golines:
      # Target maximum line length.
      # Default: 100
      max-len: 120
      # Length of a tabulation.
      # Default: 4
      tab-len: 8
      # Shorten single-line comments.
      # Default: false
      shorten-comments: true
      # Default: true
      reformat-tags: false
      # Split chained methods on the dots as opposed to the arguments.
      # Default: true
      chain-split-dots: false
