/*
 * TencentBlueKing is pleased to support the open source community by making
 * 蓝鲸智云 - 微网关(BlueKing - Micro APIGateway) available.
 * Copyright (C) 2025 Tencent. All rights reserved.
 * Licensed under the MIT License (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 *     http://opensource.org/licenses/MIT
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * We undertake not to change the open source license (MIT license) applicable
 * to the current version of the project delivered to anyone in the future.
 */

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repo

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/TencentBlueKing/blueking-micro-apigateway/apiserver/pkg/entity/model"
)

func newConsumerGroup(db *gorm.DB, opts ...gen.DOOption) consumerGroup {
	_consumerGroup := consumerGroup{}

	_consumerGroup.consumerGroupDo.UseDB(db, opts...)
	_consumerGroup.consumerGroupDo.UseModel(&model.ConsumerGroup{})

	tableName := _consumerGroup.consumerGroupDo.TableName()
	_consumerGroup.ALL = field.NewAsterisk(tableName)
	_consumerGroup.Name = field.NewString(tableName, "name")
	_consumerGroup.Creator = field.NewString(tableName, "creator")
	_consumerGroup.Updater = field.NewString(tableName, "updater")
	_consumerGroup.CreatedAt = field.NewTime(tableName, "created_at")
	_consumerGroup.UpdatedAt = field.NewTime(tableName, "updated_at")
	_consumerGroup.AutoID = field.NewInt(tableName, "auto_id")
	_consumerGroup.ID = field.NewString(tableName, "id")
	_consumerGroup.GatewayID = field.NewInt(tableName, "gateway_id")
	_consumerGroup.Config = field.NewField(tableName, "config")
	_consumerGroup.Status = field.NewString(tableName, "status")

	_consumerGroup.fillFieldMap()

	return _consumerGroup
}

type consumerGroup struct {
	consumerGroupDo consumerGroupDo

	ALL       field.Asterisk
	Name      field.String
	Creator   field.String
	Updater   field.String
	CreatedAt field.Time
	UpdatedAt field.Time
	AutoID    field.Int
	ID        field.String
	GatewayID field.Int
	Config    field.Field
	Status    field.String

	fieldMap map[string]field.Expr
}

// Table ...
func (c consumerGroup) Table(newTableName string) *consumerGroup {
	c.consumerGroupDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

// As ...
func (c consumerGroup) As(alias string) *consumerGroup {
	c.consumerGroupDo.DO = *(c.consumerGroupDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *consumerGroup) updateTableName(table string) *consumerGroup {
	c.ALL = field.NewAsterisk(table)
	c.Name = field.NewString(table, "name")
	c.Creator = field.NewString(table, "creator")
	c.Updater = field.NewString(table, "updater")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")
	c.AutoID = field.NewInt(table, "auto_id")
	c.ID = field.NewString(table, "id")
	c.GatewayID = field.NewInt(table, "gateway_id")
	c.Config = field.NewField(table, "config")
	c.Status = field.NewString(table, "status")

	c.fillFieldMap()

	return c
}

// WithContext ...
func (c *consumerGroup) WithContext(ctx context.Context) IConsumerGroupDo {
	return c.consumerGroupDo.WithContext(ctx)
}

// TableName ...
func (c consumerGroup) TableName() string { return c.consumerGroupDo.TableName() }

// Alias ...
func (c consumerGroup) Alias() string { return c.consumerGroupDo.Alias() }

// Columns ...
func (c consumerGroup) Columns(cols ...field.Expr) gen.Columns {
	return c.consumerGroupDo.Columns(cols...)
}

// GetFieldByName ...
func (c *consumerGroup) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *consumerGroup) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 10)
	c.fieldMap["name"] = c.Name
	c.fieldMap["creator"] = c.Creator
	c.fieldMap["updater"] = c.Updater
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
	c.fieldMap["auto_id"] = c.AutoID
	c.fieldMap["id"] = c.ID
	c.fieldMap["gateway_id"] = c.GatewayID
	c.fieldMap["config"] = c.Config
	c.fieldMap["status"] = c.Status
}

func (c consumerGroup) clone(db *gorm.DB) consumerGroup {
	c.consumerGroupDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c consumerGroup) replaceDB(db *gorm.DB) consumerGroup {
	c.consumerGroupDo.ReplaceDB(db)
	return c
}

type consumerGroupDo struct{ gen.DO }

// IConsumerGroupDo ...
type IConsumerGroupDo interface {
	gen.SubQuery
	Debug() IConsumerGroupDo
	WithContext(ctx context.Context) IConsumerGroupDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IConsumerGroupDo
	WriteDB() IConsumerGroupDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IConsumerGroupDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IConsumerGroupDo
	Not(conds ...gen.Condition) IConsumerGroupDo
	Or(conds ...gen.Condition) IConsumerGroupDo
	Select(conds ...field.Expr) IConsumerGroupDo
	Where(conds ...gen.Condition) IConsumerGroupDo
	Order(conds ...field.Expr) IConsumerGroupDo
	Distinct(cols ...field.Expr) IConsumerGroupDo
	Omit(cols ...field.Expr) IConsumerGroupDo
	Join(table schema.Tabler, on ...field.Expr) IConsumerGroupDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IConsumerGroupDo
	RightJoin(table schema.Tabler, on ...field.Expr) IConsumerGroupDo
	Group(cols ...field.Expr) IConsumerGroupDo
	Having(conds ...gen.Condition) IConsumerGroupDo
	Limit(limit int) IConsumerGroupDo
	Offset(offset int) IConsumerGroupDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IConsumerGroupDo
	Unscoped() IConsumerGroupDo
	Create(values ...*model.ConsumerGroup) error
	CreateInBatches(values []*model.ConsumerGroup, batchSize int) error
	Save(values ...*model.ConsumerGroup) error
	First() (*model.ConsumerGroup, error)
	Take() (*model.ConsumerGroup, error)
	Last() (*model.ConsumerGroup, error)
	Find() ([]*model.ConsumerGroup, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ConsumerGroup, err error)
	FindInBatches(result *[]*model.ConsumerGroup, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ConsumerGroup) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IConsumerGroupDo
	Assign(attrs ...field.AssignExpr) IConsumerGroupDo
	Joins(fields ...field.RelationField) IConsumerGroupDo
	Preload(fields ...field.RelationField) IConsumerGroupDo
	FirstOrInit() (*model.ConsumerGroup, error)
	FirstOrCreate() (*model.ConsumerGroup, error)
	FindByPage(offset int, limit int) (result []*model.ConsumerGroup, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IConsumerGroupDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

// Debug ...
func (c consumerGroupDo) Debug() IConsumerGroupDo {
	return c.withDO(c.DO.Debug())
}

// WithContext ...
func (c consumerGroupDo) WithContext(ctx context.Context) IConsumerGroupDo {
	return c.withDO(c.DO.WithContext(ctx))
}

// ReadDB ...
func (c consumerGroupDo) ReadDB() IConsumerGroupDo {
	return c.Clauses(dbresolver.Read)
}

// WriteDB ...
func (c consumerGroupDo) WriteDB() IConsumerGroupDo {
	return c.Clauses(dbresolver.Write)
}

// Session ...
func (c consumerGroupDo) Session(config *gorm.Session) IConsumerGroupDo {
	return c.withDO(c.DO.Session(config))
}

// Clauses ...
func (c consumerGroupDo) Clauses(conds ...clause.Expression) IConsumerGroupDo {
	return c.withDO(c.DO.Clauses(conds...))
}

// Returning ...
func (c consumerGroupDo) Returning(value interface{}, columns ...string) IConsumerGroupDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

// Not ...
func (c consumerGroupDo) Not(conds ...gen.Condition) IConsumerGroupDo {
	return c.withDO(c.DO.Not(conds...))
}

// Or ...
func (c consumerGroupDo) Or(conds ...gen.Condition) IConsumerGroupDo {
	return c.withDO(c.DO.Or(conds...))
}

// Select ...
func (c consumerGroupDo) Select(conds ...field.Expr) IConsumerGroupDo {
	return c.withDO(c.DO.Select(conds...))
}

// Where ...
func (c consumerGroupDo) Where(conds ...gen.Condition) IConsumerGroupDo {
	return c.withDO(c.DO.Where(conds...))
}

// Order ...
func (c consumerGroupDo) Order(conds ...field.Expr) IConsumerGroupDo {
	return c.withDO(c.DO.Order(conds...))
}

// Distinct ...
func (c consumerGroupDo) Distinct(cols ...field.Expr) IConsumerGroupDo {
	return c.withDO(c.DO.Distinct(cols...))
}

// Omit ...
func (c consumerGroupDo) Omit(cols ...field.Expr) IConsumerGroupDo {
	return c.withDO(c.DO.Omit(cols...))
}

// Join ...
func (c consumerGroupDo) Join(table schema.Tabler, on ...field.Expr) IConsumerGroupDo {
	return c.withDO(c.DO.Join(table, on...))
}

// LeftJoin ...
func (c consumerGroupDo) LeftJoin(table schema.Tabler, on ...field.Expr) IConsumerGroupDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

// RightJoin ...
func (c consumerGroupDo) RightJoin(table schema.Tabler, on ...field.Expr) IConsumerGroupDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

// Group ...
func (c consumerGroupDo) Group(cols ...field.Expr) IConsumerGroupDo {
	return c.withDO(c.DO.Group(cols...))
}

// Having ...
func (c consumerGroupDo) Having(conds ...gen.Condition) IConsumerGroupDo {
	return c.withDO(c.DO.Having(conds...))
}

// Limit ...
func (c consumerGroupDo) Limit(limit int) IConsumerGroupDo {
	return c.withDO(c.DO.Limit(limit))
}

// Offset ...
func (c consumerGroupDo) Offset(offset int) IConsumerGroupDo {
	return c.withDO(c.DO.Offset(offset))
}

// Scopes ...
func (c consumerGroupDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IConsumerGroupDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

// Unscoped ...
func (c consumerGroupDo) Unscoped() IConsumerGroupDo {
	return c.withDO(c.DO.Unscoped())
}

// Create ...
func (c consumerGroupDo) Create(values ...*model.ConsumerGroup) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

// CreateInBatches ...
func (c consumerGroupDo) CreateInBatches(values []*model.ConsumerGroup, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c consumerGroupDo) Save(values ...*model.ConsumerGroup) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

// First ...
func (c consumerGroupDo) First() (*model.ConsumerGroup, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConsumerGroup), nil
	}
}

// Take ...
func (c consumerGroupDo) Take() (*model.ConsumerGroup, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConsumerGroup), nil
	}
}

// Last ...
func (c consumerGroupDo) Last() (*model.ConsumerGroup, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConsumerGroup), nil
	}
}

// Find ...
func (c consumerGroupDo) Find() ([]*model.ConsumerGroup, error) {
	result, err := c.DO.Find()
	return result.([]*model.ConsumerGroup), err
}

// FindInBatch ...
func (c consumerGroupDo) FindInBatch(
	batchSize int,
	fc func(tx gen.Dao, batch int) error,
) (results []*model.ConsumerGroup, err error) {
	buf := make([]*model.ConsumerGroup, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

// FindInBatches ...
func (c consumerGroupDo) FindInBatches(
	result *[]*model.ConsumerGroup,
	batchSize int,
	fc func(tx gen.Dao, batch int) error,
) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

// Attrs ...
func (c consumerGroupDo) Attrs(attrs ...field.AssignExpr) IConsumerGroupDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

// Assign ...
func (c consumerGroupDo) Assign(attrs ...field.AssignExpr) IConsumerGroupDo {
	return c.withDO(c.DO.Assign(attrs...))
}

// Joins ...
func (c consumerGroupDo) Joins(fields ...field.RelationField) IConsumerGroupDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

// Preload ...
func (c consumerGroupDo) Preload(fields ...field.RelationField) IConsumerGroupDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

// FirstOrInit ...
func (c consumerGroupDo) FirstOrInit() (*model.ConsumerGroup, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConsumerGroup), nil
	}
}

// FirstOrCreate ...
func (c consumerGroupDo) FirstOrCreate() (*model.ConsumerGroup, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConsumerGroup), nil
	}
}

// FindByPage ...
func (c consumerGroupDo) FindByPage(offset int, limit int) (result []*model.ConsumerGroup, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

// ScanByPage ...
func (c consumerGroupDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

// Scan ...
func (c consumerGroupDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

// Delete ...
func (c consumerGroupDo) Delete(models ...*model.ConsumerGroup) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *consumerGroupDo) withDO(do gen.Dao) *consumerGroupDo {
	c.DO = *do.(*gen.DO)
	return c
}
