/*
 * TencentBlueKing is pleased to support the open source community by making
 * 蓝鲸智云 - 微网关(BlueKing - Micro APIGateway) available.
 * Copyright (C) 2025 Tencent. All rights reserved.
 * Licensed under the MIT License (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 *     http://opensource.org/licenses/MIT
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * We undertake not to change the open source license (MIT license) applicable
 * to the current version of the project delivered to anyone in the future.
 */

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repo

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/TencentBlueKing/blueking-micro-apigateway/apiserver/pkg/entity/model"
)

func newGatewayCustomPluginSchema(db *gorm.DB, opts ...gen.DOOption) gatewayCustomPluginSchema {
	_gatewayCustomPluginSchema := gatewayCustomPluginSchema{}

	_gatewayCustomPluginSchema.gatewayCustomPluginSchemaDo.UseDB(db, opts...)
	_gatewayCustomPluginSchema.gatewayCustomPluginSchemaDo.UseModel(&model.GatewayCustomPluginSchema{})

	tableName := _gatewayCustomPluginSchema.gatewayCustomPluginSchemaDo.TableName()
	_gatewayCustomPluginSchema.ALL = field.NewAsterisk(tableName)
	_gatewayCustomPluginSchema.AutoID = field.NewInt(tableName, "auto_id")
	_gatewayCustomPluginSchema.GatewayID = field.NewInt(tableName, "gateway_id")
	_gatewayCustomPluginSchema.Name = field.NewString(tableName, "name")
	_gatewayCustomPluginSchema.Schema = field.NewField(tableName, "schema")
	_gatewayCustomPluginSchema.Example = field.NewField(tableName, "example")
	_gatewayCustomPluginSchema.Creator = field.NewString(tableName, "creator")
	_gatewayCustomPluginSchema.Updater = field.NewString(tableName, "updater")
	_gatewayCustomPluginSchema.CreatedAt = field.NewTime(tableName, "created_at")
	_gatewayCustomPluginSchema.UpdatedAt = field.NewTime(tableName, "updated_at")

	_gatewayCustomPluginSchema.fillFieldMap()

	return _gatewayCustomPluginSchema
}

type gatewayCustomPluginSchema struct {
	gatewayCustomPluginSchemaDo gatewayCustomPluginSchemaDo

	ALL       field.Asterisk
	AutoID    field.Int
	GatewayID field.Int
	Name      field.String
	Schema    field.Field
	Example   field.Field
	Creator   field.String
	Updater   field.String
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

// Table ...
func (g gatewayCustomPluginSchema) Table(newTableName string) *gatewayCustomPluginSchema {
	g.gatewayCustomPluginSchemaDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

// As ...
func (g gatewayCustomPluginSchema) As(alias string) *gatewayCustomPluginSchema {
	g.gatewayCustomPluginSchemaDo.DO = *(g.gatewayCustomPluginSchemaDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *gatewayCustomPluginSchema) updateTableName(table string) *gatewayCustomPluginSchema {
	g.ALL = field.NewAsterisk(table)
	g.AutoID = field.NewInt(table, "auto_id")
	g.GatewayID = field.NewInt(table, "gateway_id")
	g.Name = field.NewString(table, "name")
	g.Schema = field.NewField(table, "schema")
	g.Example = field.NewField(table, "example")
	g.Creator = field.NewString(table, "creator")
	g.Updater = field.NewString(table, "updater")
	g.CreatedAt = field.NewTime(table, "created_at")
	g.UpdatedAt = field.NewTime(table, "updated_at")

	g.fillFieldMap()

	return g
}

// WithContext ...
func (g *gatewayCustomPluginSchema) WithContext(ctx context.Context) IGatewayCustomPluginSchemaDo {
	return g.gatewayCustomPluginSchemaDo.WithContext(ctx)
}

// TableName ...
func (g gatewayCustomPluginSchema) TableName() string {
	return g.gatewayCustomPluginSchemaDo.TableName()
}

// Alias ...
func (g gatewayCustomPluginSchema) Alias() string { return g.gatewayCustomPluginSchemaDo.Alias() }

// Columns ...
func (g gatewayCustomPluginSchema) Columns(cols ...field.Expr) gen.Columns {
	return g.gatewayCustomPluginSchemaDo.Columns(cols...)
}

// GetFieldByName ...
func (g *gatewayCustomPluginSchema) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *gatewayCustomPluginSchema) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 9)
	g.fieldMap["auto_id"] = g.AutoID
	g.fieldMap["gateway_id"] = g.GatewayID
	g.fieldMap["name"] = g.Name
	g.fieldMap["schema"] = g.Schema
	g.fieldMap["example"] = g.Example
	g.fieldMap["creator"] = g.Creator
	g.fieldMap["updater"] = g.Updater
	g.fieldMap["created_at"] = g.CreatedAt
	g.fieldMap["updated_at"] = g.UpdatedAt
}

func (g gatewayCustomPluginSchema) clone(db *gorm.DB) gatewayCustomPluginSchema {
	g.gatewayCustomPluginSchemaDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g gatewayCustomPluginSchema) replaceDB(db *gorm.DB) gatewayCustomPluginSchema {
	g.gatewayCustomPluginSchemaDo.ReplaceDB(db)
	return g
}

type gatewayCustomPluginSchemaDo struct{ gen.DO }

// IGatewayCustomPluginSchemaDo ...
type IGatewayCustomPluginSchemaDo interface {
	gen.SubQuery
	Debug() IGatewayCustomPluginSchemaDo
	WithContext(ctx context.Context) IGatewayCustomPluginSchemaDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IGatewayCustomPluginSchemaDo
	WriteDB() IGatewayCustomPluginSchemaDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IGatewayCustomPluginSchemaDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IGatewayCustomPluginSchemaDo
	Not(conds ...gen.Condition) IGatewayCustomPluginSchemaDo
	Or(conds ...gen.Condition) IGatewayCustomPluginSchemaDo
	Select(conds ...field.Expr) IGatewayCustomPluginSchemaDo
	Where(conds ...gen.Condition) IGatewayCustomPluginSchemaDo
	Order(conds ...field.Expr) IGatewayCustomPluginSchemaDo
	Distinct(cols ...field.Expr) IGatewayCustomPluginSchemaDo
	Omit(cols ...field.Expr) IGatewayCustomPluginSchemaDo
	Join(table schema.Tabler, on ...field.Expr) IGatewayCustomPluginSchemaDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IGatewayCustomPluginSchemaDo
	RightJoin(table schema.Tabler, on ...field.Expr) IGatewayCustomPluginSchemaDo
	Group(cols ...field.Expr) IGatewayCustomPluginSchemaDo
	Having(conds ...gen.Condition) IGatewayCustomPluginSchemaDo
	Limit(limit int) IGatewayCustomPluginSchemaDo
	Offset(offset int) IGatewayCustomPluginSchemaDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IGatewayCustomPluginSchemaDo
	Unscoped() IGatewayCustomPluginSchemaDo
	Create(values ...*model.GatewayCustomPluginSchema) error
	CreateInBatches(values []*model.GatewayCustomPluginSchema, batchSize int) error
	Save(values ...*model.GatewayCustomPluginSchema) error
	First() (*model.GatewayCustomPluginSchema, error)
	Take() (*model.GatewayCustomPluginSchema, error)
	Last() (*model.GatewayCustomPluginSchema, error)
	Find() ([]*model.GatewayCustomPluginSchema, error)
	FindInBatch(
		batchSize int,
		fc func(tx gen.Dao, batch int) error,
	) (results []*model.GatewayCustomPluginSchema, err error)
	FindInBatches(
		result *[]*model.GatewayCustomPluginSchema,
		batchSize int,
		fc func(tx gen.Dao, batch int) error,
	) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.GatewayCustomPluginSchema) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IGatewayCustomPluginSchemaDo
	Assign(attrs ...field.AssignExpr) IGatewayCustomPluginSchemaDo
	Joins(fields ...field.RelationField) IGatewayCustomPluginSchemaDo
	Preload(fields ...field.RelationField) IGatewayCustomPluginSchemaDo
	FirstOrInit() (*model.GatewayCustomPluginSchema, error)
	FirstOrCreate() (*model.GatewayCustomPluginSchema, error)
	FindByPage(offset int, limit int) (result []*model.GatewayCustomPluginSchema, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IGatewayCustomPluginSchemaDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

// Debug ...
func (g gatewayCustomPluginSchemaDo) Debug() IGatewayCustomPluginSchemaDo {
	return g.withDO(g.DO.Debug())
}

// WithContext ...
func (g gatewayCustomPluginSchemaDo) WithContext(ctx context.Context) IGatewayCustomPluginSchemaDo {
	return g.withDO(g.DO.WithContext(ctx))
}

// ReadDB ...
func (g gatewayCustomPluginSchemaDo) ReadDB() IGatewayCustomPluginSchemaDo {
	return g.Clauses(dbresolver.Read)
}

// WriteDB ...
func (g gatewayCustomPluginSchemaDo) WriteDB() IGatewayCustomPluginSchemaDo {
	return g.Clauses(dbresolver.Write)
}

// Session ...
func (g gatewayCustomPluginSchemaDo) Session(config *gorm.Session) IGatewayCustomPluginSchemaDo {
	return g.withDO(g.DO.Session(config))
}

// Clauses ...
func (g gatewayCustomPluginSchemaDo) Clauses(conds ...clause.Expression) IGatewayCustomPluginSchemaDo {
	return g.withDO(g.DO.Clauses(conds...))
}

// Returning ...
func (g gatewayCustomPluginSchemaDo) Returning(value interface{}, columns ...string) IGatewayCustomPluginSchemaDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

// Not ...
func (g gatewayCustomPluginSchemaDo) Not(conds ...gen.Condition) IGatewayCustomPluginSchemaDo {
	return g.withDO(g.DO.Not(conds...))
}

// Or ...
func (g gatewayCustomPluginSchemaDo) Or(conds ...gen.Condition) IGatewayCustomPluginSchemaDo {
	return g.withDO(g.DO.Or(conds...))
}

// Select ...
func (g gatewayCustomPluginSchemaDo) Select(conds ...field.Expr) IGatewayCustomPluginSchemaDo {
	return g.withDO(g.DO.Select(conds...))
}

// Where ...
func (g gatewayCustomPluginSchemaDo) Where(conds ...gen.Condition) IGatewayCustomPluginSchemaDo {
	return g.withDO(g.DO.Where(conds...))
}

// Order ...
func (g gatewayCustomPluginSchemaDo) Order(conds ...field.Expr) IGatewayCustomPluginSchemaDo {
	return g.withDO(g.DO.Order(conds...))
}

// Distinct ...
func (g gatewayCustomPluginSchemaDo) Distinct(cols ...field.Expr) IGatewayCustomPluginSchemaDo {
	return g.withDO(g.DO.Distinct(cols...))
}

// Omit ...
func (g gatewayCustomPluginSchemaDo) Omit(cols ...field.Expr) IGatewayCustomPluginSchemaDo {
	return g.withDO(g.DO.Omit(cols...))
}

// Join ...
func (g gatewayCustomPluginSchemaDo) Join(table schema.Tabler, on ...field.Expr) IGatewayCustomPluginSchemaDo {
	return g.withDO(g.DO.Join(table, on...))
}

// LeftJoin ...
func (g gatewayCustomPluginSchemaDo) LeftJoin(table schema.Tabler, on ...field.Expr) IGatewayCustomPluginSchemaDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

// RightJoin ...
func (g gatewayCustomPluginSchemaDo) RightJoin(table schema.Tabler, on ...field.Expr) IGatewayCustomPluginSchemaDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

// Group ...
func (g gatewayCustomPluginSchemaDo) Group(cols ...field.Expr) IGatewayCustomPluginSchemaDo {
	return g.withDO(g.DO.Group(cols...))
}

// Having ...
func (g gatewayCustomPluginSchemaDo) Having(conds ...gen.Condition) IGatewayCustomPluginSchemaDo {
	return g.withDO(g.DO.Having(conds...))
}

// Limit ...
func (g gatewayCustomPluginSchemaDo) Limit(limit int) IGatewayCustomPluginSchemaDo {
	return g.withDO(g.DO.Limit(limit))
}

// Offset ...
func (g gatewayCustomPluginSchemaDo) Offset(offset int) IGatewayCustomPluginSchemaDo {
	return g.withDO(g.DO.Offset(offset))
}

// Scopes ...
func (g gatewayCustomPluginSchemaDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IGatewayCustomPluginSchemaDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

// Unscoped ...
func (g gatewayCustomPluginSchemaDo) Unscoped() IGatewayCustomPluginSchemaDo {
	return g.withDO(g.DO.Unscoped())
}

// Create ...
func (g gatewayCustomPluginSchemaDo) Create(values ...*model.GatewayCustomPluginSchema) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

// CreateInBatches ...
func (g gatewayCustomPluginSchemaDo) CreateInBatches(values []*model.GatewayCustomPluginSchema, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g gatewayCustomPluginSchemaDo) Save(values ...*model.GatewayCustomPluginSchema) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

// First ...
func (g gatewayCustomPluginSchemaDo) First() (*model.GatewayCustomPluginSchema, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.GatewayCustomPluginSchema), nil
	}
}

// Take ...
func (g gatewayCustomPluginSchemaDo) Take() (*model.GatewayCustomPluginSchema, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.GatewayCustomPluginSchema), nil
	}
}

// Last ...
func (g gatewayCustomPluginSchemaDo) Last() (*model.GatewayCustomPluginSchema, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.GatewayCustomPluginSchema), nil
	}
}

// Find ...
func (g gatewayCustomPluginSchemaDo) Find() ([]*model.GatewayCustomPluginSchema, error) {
	result, err := g.DO.Find()
	return result.([]*model.GatewayCustomPluginSchema), err
}

// FindInBatch ...
func (g gatewayCustomPluginSchemaDo) FindInBatch(
	batchSize int,
	fc func(tx gen.Dao, batch int) error,
) (results []*model.GatewayCustomPluginSchema, err error) {
	buf := make([]*model.GatewayCustomPluginSchema, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

// FindInBatches ...
func (g gatewayCustomPluginSchemaDo) FindInBatches(
	result *[]*model.GatewayCustomPluginSchema,
	batchSize int,
	fc func(tx gen.Dao, batch int) error,
) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

// Attrs ...
func (g gatewayCustomPluginSchemaDo) Attrs(attrs ...field.AssignExpr) IGatewayCustomPluginSchemaDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

// Assign ...
func (g gatewayCustomPluginSchemaDo) Assign(attrs ...field.AssignExpr) IGatewayCustomPluginSchemaDo {
	return g.withDO(g.DO.Assign(attrs...))
}

// Joins ...
func (g gatewayCustomPluginSchemaDo) Joins(fields ...field.RelationField) IGatewayCustomPluginSchemaDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

// Preload ...
func (g gatewayCustomPluginSchemaDo) Preload(fields ...field.RelationField) IGatewayCustomPluginSchemaDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

// FirstOrInit ...
func (g gatewayCustomPluginSchemaDo) FirstOrInit() (*model.GatewayCustomPluginSchema, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.GatewayCustomPluginSchema), nil
	}
}

// FirstOrCreate ...
func (g gatewayCustomPluginSchemaDo) FirstOrCreate() (*model.GatewayCustomPluginSchema, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.GatewayCustomPluginSchema), nil
	}
}

// FindByPage ...
func (g gatewayCustomPluginSchemaDo) FindByPage(
	offset int,
	limit int,
) (result []*model.GatewayCustomPluginSchema, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

// ScanByPage ...
func (g gatewayCustomPluginSchemaDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

// Scan ...
func (g gatewayCustomPluginSchemaDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

// Delete ...
func (g gatewayCustomPluginSchemaDo) Delete(
	models ...*model.GatewayCustomPluginSchema,
) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *gatewayCustomPluginSchemaDo) withDO(do gen.Dao) *gatewayCustomPluginSchemaDo {
	g.DO = *do.(*gen.DO)
	return g
}
