/*
 * TencentBlueKing is pleased to support the open source community by making
 * 蓝鲸智云 - 微网关(BlueKing - Micro APIGateway) available.
 * Copyright (C) 2025 Tencent. All rights reserved.
 * Licensed under the MIT License (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 *     http://opensource.org/licenses/MIT
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * We undertake not to change the open source license (MIT license) applicable
 * to the current version of the project delivered to anyone in the future.
 */

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repo

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/TencentBlueKing/blueking-micro-apigateway/apiserver/pkg/entity/model"
)

func newGlobalRule(db *gorm.DB, opts ...gen.DOOption) globalRule {
	_globalRule := globalRule{}

	_globalRule.globalRuleDo.UseDB(db, opts...)
	_globalRule.globalRuleDo.UseModel(&model.GlobalRule{})

	tableName := _globalRule.globalRuleDo.TableName()
	_globalRule.ALL = field.NewAsterisk(tableName)
	_globalRule.Name = field.NewString(tableName, "name")
	_globalRule.Creator = field.NewString(tableName, "creator")
	_globalRule.Updater = field.NewString(tableName, "updater")
	_globalRule.CreatedAt = field.NewTime(tableName, "created_at")
	_globalRule.UpdatedAt = field.NewTime(tableName, "updated_at")
	_globalRule.AutoID = field.NewInt(tableName, "auto_id")
	_globalRule.ID = field.NewString(tableName, "id")
	_globalRule.GatewayID = field.NewInt(tableName, "gateway_id")
	_globalRule.Config = field.NewField(tableName, "config")
	_globalRule.Status = field.NewString(tableName, "status")

	_globalRule.fillFieldMap()

	return _globalRule
}

type globalRule struct {
	globalRuleDo globalRuleDo

	ALL       field.Asterisk
	Name      field.String
	Creator   field.String
	Updater   field.String
	CreatedAt field.Time
	UpdatedAt field.Time
	AutoID    field.Int
	ID        field.String
	GatewayID field.Int
	Config    field.Field
	Status    field.String

	fieldMap map[string]field.Expr
}

// Table ...
func (g globalRule) Table(newTableName string) *globalRule {
	g.globalRuleDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

// As ...
func (g globalRule) As(alias string) *globalRule {
	g.globalRuleDo.DO = *(g.globalRuleDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *globalRule) updateTableName(table string) *globalRule {
	g.ALL = field.NewAsterisk(table)
	g.Name = field.NewString(table, "name")
	g.Creator = field.NewString(table, "creator")
	g.Updater = field.NewString(table, "updater")
	g.CreatedAt = field.NewTime(table, "created_at")
	g.UpdatedAt = field.NewTime(table, "updated_at")
	g.AutoID = field.NewInt(table, "auto_id")
	g.ID = field.NewString(table, "id")
	g.GatewayID = field.NewInt(table, "gateway_id")
	g.Config = field.NewField(table, "config")
	g.Status = field.NewString(table, "status")

	g.fillFieldMap()

	return g
}

// WithContext ...
func (g *globalRule) WithContext(ctx context.Context) IGlobalRuleDo {
	return g.globalRuleDo.WithContext(ctx)
}

// TableName ...
func (g globalRule) TableName() string { return g.globalRuleDo.TableName() }

// Alias ...
func (g globalRule) Alias() string { return g.globalRuleDo.Alias() }

// Columns ...
func (g globalRule) Columns(cols ...field.Expr) gen.Columns { return g.globalRuleDo.Columns(cols...) }

// GetFieldByName ...
func (g *globalRule) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *globalRule) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 10)
	g.fieldMap["name"] = g.Name
	g.fieldMap["creator"] = g.Creator
	g.fieldMap["updater"] = g.Updater
	g.fieldMap["created_at"] = g.CreatedAt
	g.fieldMap["updated_at"] = g.UpdatedAt
	g.fieldMap["auto_id"] = g.AutoID
	g.fieldMap["id"] = g.ID
	g.fieldMap["gateway_id"] = g.GatewayID
	g.fieldMap["config"] = g.Config
	g.fieldMap["status"] = g.Status
}

func (g globalRule) clone(db *gorm.DB) globalRule {
	g.globalRuleDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g globalRule) replaceDB(db *gorm.DB) globalRule {
	g.globalRuleDo.ReplaceDB(db)
	return g
}

type globalRuleDo struct{ gen.DO }

// IGlobalRuleDo ...
type IGlobalRuleDo interface {
	gen.SubQuery
	Debug() IGlobalRuleDo
	WithContext(ctx context.Context) IGlobalRuleDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IGlobalRuleDo
	WriteDB() IGlobalRuleDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IGlobalRuleDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IGlobalRuleDo
	Not(conds ...gen.Condition) IGlobalRuleDo
	Or(conds ...gen.Condition) IGlobalRuleDo
	Select(conds ...field.Expr) IGlobalRuleDo
	Where(conds ...gen.Condition) IGlobalRuleDo
	Order(conds ...field.Expr) IGlobalRuleDo
	Distinct(cols ...field.Expr) IGlobalRuleDo
	Omit(cols ...field.Expr) IGlobalRuleDo
	Join(table schema.Tabler, on ...field.Expr) IGlobalRuleDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IGlobalRuleDo
	RightJoin(table schema.Tabler, on ...field.Expr) IGlobalRuleDo
	Group(cols ...field.Expr) IGlobalRuleDo
	Having(conds ...gen.Condition) IGlobalRuleDo
	Limit(limit int) IGlobalRuleDo
	Offset(offset int) IGlobalRuleDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IGlobalRuleDo
	Unscoped() IGlobalRuleDo
	Create(values ...*model.GlobalRule) error
	CreateInBatches(values []*model.GlobalRule, batchSize int) error
	Save(values ...*model.GlobalRule) error
	First() (*model.GlobalRule, error)
	Take() (*model.GlobalRule, error)
	Last() (*model.GlobalRule, error)
	Find() ([]*model.GlobalRule, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GlobalRule, err error)
	FindInBatches(result *[]*model.GlobalRule, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.GlobalRule) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IGlobalRuleDo
	Assign(attrs ...field.AssignExpr) IGlobalRuleDo
	Joins(fields ...field.RelationField) IGlobalRuleDo
	Preload(fields ...field.RelationField) IGlobalRuleDo
	FirstOrInit() (*model.GlobalRule, error)
	FirstOrCreate() (*model.GlobalRule, error)
	FindByPage(offset int, limit int) (result []*model.GlobalRule, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IGlobalRuleDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

// Debug ...
func (g globalRuleDo) Debug() IGlobalRuleDo {
	return g.withDO(g.DO.Debug())
}

// WithContext ...
func (g globalRuleDo) WithContext(ctx context.Context) IGlobalRuleDo {
	return g.withDO(g.DO.WithContext(ctx))
}

// ReadDB ...
func (g globalRuleDo) ReadDB() IGlobalRuleDo {
	return g.Clauses(dbresolver.Read)
}

// WriteDB ...
func (g globalRuleDo) WriteDB() IGlobalRuleDo {
	return g.Clauses(dbresolver.Write)
}

// Session ...
func (g globalRuleDo) Session(config *gorm.Session) IGlobalRuleDo {
	return g.withDO(g.DO.Session(config))
}

// Clauses ...
func (g globalRuleDo) Clauses(conds ...clause.Expression) IGlobalRuleDo {
	return g.withDO(g.DO.Clauses(conds...))
}

// Returning ...
func (g globalRuleDo) Returning(value interface{}, columns ...string) IGlobalRuleDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

// Not ...
func (g globalRuleDo) Not(conds ...gen.Condition) IGlobalRuleDo {
	return g.withDO(g.DO.Not(conds...))
}

// Or ...
func (g globalRuleDo) Or(conds ...gen.Condition) IGlobalRuleDo {
	return g.withDO(g.DO.Or(conds...))
}

// Select ...
func (g globalRuleDo) Select(conds ...field.Expr) IGlobalRuleDo {
	return g.withDO(g.DO.Select(conds...))
}

// Where ...
func (g globalRuleDo) Where(conds ...gen.Condition) IGlobalRuleDo {
	return g.withDO(g.DO.Where(conds...))
}

// Order ...
func (g globalRuleDo) Order(conds ...field.Expr) IGlobalRuleDo {
	return g.withDO(g.DO.Order(conds...))
}

// Distinct ...
func (g globalRuleDo) Distinct(cols ...field.Expr) IGlobalRuleDo {
	return g.withDO(g.DO.Distinct(cols...))
}

// Omit ...
func (g globalRuleDo) Omit(cols ...field.Expr) IGlobalRuleDo {
	return g.withDO(g.DO.Omit(cols...))
}

// Join ...
func (g globalRuleDo) Join(table schema.Tabler, on ...field.Expr) IGlobalRuleDo {
	return g.withDO(g.DO.Join(table, on...))
}

// LeftJoin ...
func (g globalRuleDo) LeftJoin(table schema.Tabler, on ...field.Expr) IGlobalRuleDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

// RightJoin ...
func (g globalRuleDo) RightJoin(table schema.Tabler, on ...field.Expr) IGlobalRuleDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

// Group ...
func (g globalRuleDo) Group(cols ...field.Expr) IGlobalRuleDo {
	return g.withDO(g.DO.Group(cols...))
}

// Having ...
func (g globalRuleDo) Having(conds ...gen.Condition) IGlobalRuleDo {
	return g.withDO(g.DO.Having(conds...))
}

// Limit ...
func (g globalRuleDo) Limit(limit int) IGlobalRuleDo {
	return g.withDO(g.DO.Limit(limit))
}

// Offset ...
func (g globalRuleDo) Offset(offset int) IGlobalRuleDo {
	return g.withDO(g.DO.Offset(offset))
}

// Scopes ...
func (g globalRuleDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IGlobalRuleDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

// Unscoped ...
func (g globalRuleDo) Unscoped() IGlobalRuleDo {
	return g.withDO(g.DO.Unscoped())
}

// Create ...
func (g globalRuleDo) Create(values ...*model.GlobalRule) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

// CreateInBatches ...
func (g globalRuleDo) CreateInBatches(values []*model.GlobalRule, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g globalRuleDo) Save(values ...*model.GlobalRule) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

// First ...
func (g globalRuleDo) First() (*model.GlobalRule, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.GlobalRule), nil
	}
}

// Take ...
func (g globalRuleDo) Take() (*model.GlobalRule, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.GlobalRule), nil
	}
}

// Last ...
func (g globalRuleDo) Last() (*model.GlobalRule, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.GlobalRule), nil
	}
}

// Find ...
func (g globalRuleDo) Find() ([]*model.GlobalRule, error) {
	result, err := g.DO.Find()
	return result.([]*model.GlobalRule), err
}

// FindInBatch ...
func (g globalRuleDo) FindInBatch(
	batchSize int,
	fc func(tx gen.Dao, batch int) error,
) (results []*model.GlobalRule, err error) {
	buf := make([]*model.GlobalRule, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

// FindInBatches ...
func (g globalRuleDo) FindInBatches(
	result *[]*model.GlobalRule,
	batchSize int,
	fc func(tx gen.Dao, batch int) error,
) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

// Attrs ...
func (g globalRuleDo) Attrs(attrs ...field.AssignExpr) IGlobalRuleDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

// Assign ...
func (g globalRuleDo) Assign(attrs ...field.AssignExpr) IGlobalRuleDo {
	return g.withDO(g.DO.Assign(attrs...))
}

// Joins ...
func (g globalRuleDo) Joins(fields ...field.RelationField) IGlobalRuleDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

// Preload ...
func (g globalRuleDo) Preload(fields ...field.RelationField) IGlobalRuleDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

// FirstOrInit ...
func (g globalRuleDo) FirstOrInit() (*model.GlobalRule, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.GlobalRule), nil
	}
}

// FirstOrCreate ...
func (g globalRuleDo) FirstOrCreate() (*model.GlobalRule, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.GlobalRule), nil
	}
}

// FindByPage ...
func (g globalRuleDo) FindByPage(offset int, limit int) (result []*model.GlobalRule, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

// ScanByPage ...
func (g globalRuleDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

// Scan ...
func (g globalRuleDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

// Delete ...
func (g globalRuleDo) Delete(models ...*model.GlobalRule) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *globalRuleDo) withDO(do gen.Dao) *globalRuleDo {
	g.DO = *do.(*gen.DO)
	return g
}
