/*
 * TencentBlueKing is pleased to support the open source community by making
 * 蓝鲸智云 - 微网关(BlueKing - Micro APIGateway) available.
 * Copyright (C) 2025 Tencent. All rights reserved.
 * Licensed under the MIT License (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 *     http://opensource.org/licenses/MIT
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * We undertake not to change the open source license (MIT license) applicable
 * to the current version of the project delivered to anyone in the future.
 */

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repo

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/TencentBlueKing/blueking-micro-apigateway/apiserver/pkg/entity/model"
)

func newService(db *gorm.DB, opts ...gen.DOOption) service {
	_service := service{}

	_service.serviceDo.UseDB(db, opts...)
	_service.serviceDo.UseModel(&model.Service{})

	tableName := _service.serviceDo.TableName()
	_service.ALL = field.NewAsterisk(tableName)
	_service.Name = field.NewString(tableName, "name")
	_service.UpstreamID = field.NewString(tableName, "upstream_id")
	_service.Creator = field.NewString(tableName, "creator")
	_service.Updater = field.NewString(tableName, "updater")
	_service.CreatedAt = field.NewTime(tableName, "created_at")
	_service.UpdatedAt = field.NewTime(tableName, "updated_at")
	_service.AutoID = field.NewInt(tableName, "auto_id")
	_service.ID = field.NewString(tableName, "id")
	_service.GatewayID = field.NewInt(tableName, "gateway_id")
	_service.Config = field.NewField(tableName, "config")
	_service.Status = field.NewString(tableName, "status")

	_service.fillFieldMap()

	return _service
}

type service struct {
	serviceDo serviceDo

	ALL        field.Asterisk
	Name       field.String
	UpstreamID field.String
	Creator    field.String
	Updater    field.String
	CreatedAt  field.Time
	UpdatedAt  field.Time
	AutoID     field.Int
	ID         field.String
	GatewayID  field.Int
	Config     field.Field
	Status     field.String

	fieldMap map[string]field.Expr
}

// Table ...
func (s service) Table(newTableName string) *service {
	s.serviceDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

// As ...
func (s service) As(alias string) *service {
	s.serviceDo.DO = *(s.serviceDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *service) updateTableName(table string) *service {
	s.ALL = field.NewAsterisk(table)
	s.Name = field.NewString(table, "name")
	s.UpstreamID = field.NewString(table, "upstream_id")
	s.Creator = field.NewString(table, "creator")
	s.Updater = field.NewString(table, "updater")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.AutoID = field.NewInt(table, "auto_id")
	s.ID = field.NewString(table, "id")
	s.GatewayID = field.NewInt(table, "gateway_id")
	s.Config = field.NewField(table, "config")
	s.Status = field.NewString(table, "status")

	s.fillFieldMap()

	return s
}

// WithContext ...
func (s *service) WithContext(ctx context.Context) IServiceDo { return s.serviceDo.WithContext(ctx) }

// TableName ...
func (s service) TableName() string { return s.serviceDo.TableName() }

// Alias ...
func (s service) Alias() string { return s.serviceDo.Alias() }

// Columns ...
func (s service) Columns(cols ...field.Expr) gen.Columns { return s.serviceDo.Columns(cols...) }

// GetFieldByName ...
func (s *service) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *service) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 11)
	s.fieldMap["name"] = s.Name
	s.fieldMap["upstream_id"] = s.UpstreamID
	s.fieldMap["creator"] = s.Creator
	s.fieldMap["updater"] = s.Updater
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["auto_id"] = s.AutoID
	s.fieldMap["id"] = s.ID
	s.fieldMap["gateway_id"] = s.GatewayID
	s.fieldMap["config"] = s.Config
	s.fieldMap["status"] = s.Status
}

func (s service) clone(db *gorm.DB) service {
	s.serviceDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s service) replaceDB(db *gorm.DB) service {
	s.serviceDo.ReplaceDB(db)
	return s
}

type serviceDo struct{ gen.DO }

// IServiceDo ...
type IServiceDo interface {
	gen.SubQuery
	Debug() IServiceDo
	WithContext(ctx context.Context) IServiceDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IServiceDo
	WriteDB() IServiceDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IServiceDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IServiceDo
	Not(conds ...gen.Condition) IServiceDo
	Or(conds ...gen.Condition) IServiceDo
	Select(conds ...field.Expr) IServiceDo
	Where(conds ...gen.Condition) IServiceDo
	Order(conds ...field.Expr) IServiceDo
	Distinct(cols ...field.Expr) IServiceDo
	Omit(cols ...field.Expr) IServiceDo
	Join(table schema.Tabler, on ...field.Expr) IServiceDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IServiceDo
	RightJoin(table schema.Tabler, on ...field.Expr) IServiceDo
	Group(cols ...field.Expr) IServiceDo
	Having(conds ...gen.Condition) IServiceDo
	Limit(limit int) IServiceDo
	Offset(offset int) IServiceDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IServiceDo
	Unscoped() IServiceDo
	Create(values ...*model.Service) error
	CreateInBatches(values []*model.Service, batchSize int) error
	Save(values ...*model.Service) error
	First() (*model.Service, error)
	Take() (*model.Service, error)
	Last() (*model.Service, error)
	Find() ([]*model.Service, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Service, err error)
	FindInBatches(result *[]*model.Service, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Service) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IServiceDo
	Assign(attrs ...field.AssignExpr) IServiceDo
	Joins(fields ...field.RelationField) IServiceDo
	Preload(fields ...field.RelationField) IServiceDo
	FirstOrInit() (*model.Service, error)
	FirstOrCreate() (*model.Service, error)
	FindByPage(offset int, limit int) (result []*model.Service, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IServiceDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

// Debug ...
func (s serviceDo) Debug() IServiceDo {
	return s.withDO(s.DO.Debug())
}

// WithContext ...
func (s serviceDo) WithContext(ctx context.Context) IServiceDo {
	return s.withDO(s.DO.WithContext(ctx))
}

// ReadDB ...
func (s serviceDo) ReadDB() IServiceDo {
	return s.Clauses(dbresolver.Read)
}

// WriteDB ...
func (s serviceDo) WriteDB() IServiceDo {
	return s.Clauses(dbresolver.Write)
}

// Session ...
func (s serviceDo) Session(config *gorm.Session) IServiceDo {
	return s.withDO(s.DO.Session(config))
}

// Clauses ...
func (s serviceDo) Clauses(conds ...clause.Expression) IServiceDo {
	return s.withDO(s.DO.Clauses(conds...))
}

// Returning ...
func (s serviceDo) Returning(value interface{}, columns ...string) IServiceDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

// Not ...
func (s serviceDo) Not(conds ...gen.Condition) IServiceDo {
	return s.withDO(s.DO.Not(conds...))
}

// Or ...
func (s serviceDo) Or(conds ...gen.Condition) IServiceDo {
	return s.withDO(s.DO.Or(conds...))
}

// Select ...
func (s serviceDo) Select(conds ...field.Expr) IServiceDo {
	return s.withDO(s.DO.Select(conds...))
}

// Where ...
func (s serviceDo) Where(conds ...gen.Condition) IServiceDo {
	return s.withDO(s.DO.Where(conds...))
}

// Order ...
func (s serviceDo) Order(conds ...field.Expr) IServiceDo {
	return s.withDO(s.DO.Order(conds...))
}

// Distinct ...
func (s serviceDo) Distinct(cols ...field.Expr) IServiceDo {
	return s.withDO(s.DO.Distinct(cols...))
}

// Omit ...
func (s serviceDo) Omit(cols ...field.Expr) IServiceDo {
	return s.withDO(s.DO.Omit(cols...))
}

// Join ...
func (s serviceDo) Join(table schema.Tabler, on ...field.Expr) IServiceDo {
	return s.withDO(s.DO.Join(table, on...))
}

// LeftJoin ...
func (s serviceDo) LeftJoin(table schema.Tabler, on ...field.Expr) IServiceDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

// RightJoin ...
func (s serviceDo) RightJoin(table schema.Tabler, on ...field.Expr) IServiceDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

// Group ...
func (s serviceDo) Group(cols ...field.Expr) IServiceDo {
	return s.withDO(s.DO.Group(cols...))
}

// Having ...
func (s serviceDo) Having(conds ...gen.Condition) IServiceDo {
	return s.withDO(s.DO.Having(conds...))
}

// Limit ...
func (s serviceDo) Limit(limit int) IServiceDo {
	return s.withDO(s.DO.Limit(limit))
}

// Offset ...
func (s serviceDo) Offset(offset int) IServiceDo {
	return s.withDO(s.DO.Offset(offset))
}

// Scopes ...
func (s serviceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IServiceDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

// Unscoped ...
func (s serviceDo) Unscoped() IServiceDo {
	return s.withDO(s.DO.Unscoped())
}

// Create ...
func (s serviceDo) Create(values ...*model.Service) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

// CreateInBatches ...
func (s serviceDo) CreateInBatches(values []*model.Service, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s serviceDo) Save(values ...*model.Service) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

// First ...
func (s serviceDo) First() (*model.Service, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Service), nil
	}
}

// Take ...
func (s serviceDo) Take() (*model.Service, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Service), nil
	}
}

// Last ...
func (s serviceDo) Last() (*model.Service, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Service), nil
	}
}

// Find ...
func (s serviceDo) Find() ([]*model.Service, error) {
	result, err := s.DO.Find()
	return result.([]*model.Service), err
}

// FindInBatch ...
func (s serviceDo) FindInBatch(
	batchSize int,
	fc func(tx gen.Dao, batch int) error,
) (results []*model.Service, err error) {
	buf := make([]*model.Service, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

// FindInBatches ...
func (s serviceDo) FindInBatches(result *[]*model.Service, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

// Attrs ...
func (s serviceDo) Attrs(attrs ...field.AssignExpr) IServiceDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

// Assign ...
func (s serviceDo) Assign(attrs ...field.AssignExpr) IServiceDo {
	return s.withDO(s.DO.Assign(attrs...))
}

// Joins ...
func (s serviceDo) Joins(fields ...field.RelationField) IServiceDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

// Preload ...
func (s serviceDo) Preload(fields ...field.RelationField) IServiceDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

// FirstOrInit ...
func (s serviceDo) FirstOrInit() (*model.Service, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Service), nil
	}
}

// FirstOrCreate ...
func (s serviceDo) FirstOrCreate() (*model.Service, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Service), nil
	}
}

// FindByPage ...
func (s serviceDo) FindByPage(offset int, limit int) (result []*model.Service, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

// ScanByPage ...
func (s serviceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

// Scan ...
func (s serviceDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

// Delete ...
func (s serviceDo) Delete(models ...*model.Service) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *serviceDo) withDO(do gen.Dao) *serviceDo {
	s.DO = *do.(*gen.DO)
	return s
}
