/*
 * TencentBlueKing is pleased to support the open source community by making
 * 蓝鲸智云 - 微网关(BlueKing - Micro APIGateway) available.
 * Copyright (C) 2025 Tencent. All rights reserved.
 * Licensed under the MIT License (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 *     http://opensource.org/licenses/MIT
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * We undertake not to change the open source license (MIT license) applicable
 * to the current version of the project delivered to anyone in the future.
 */

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repo

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/TencentBlueKing/blueking-micro-apigateway/apiserver/pkg/entity/model"
)

func newSSL(db *gorm.DB, opts ...gen.DOOption) sSL {
	_sSL := sSL{}

	_sSL.sSLDo.UseDB(db, opts...)
	_sSL.sSLDo.UseModel(&model.SSL{})

	tableName := _sSL.sSLDo.TableName()
	_sSL.ALL = field.NewAsterisk(tableName)
	_sSL.Name = field.NewString(tableName, "name")
	_sSL.Creator = field.NewString(tableName, "creator")
	_sSL.Updater = field.NewString(tableName, "updater")
	_sSL.CreatedAt = field.NewTime(tableName, "created_at")
	_sSL.UpdatedAt = field.NewTime(tableName, "updated_at")
	_sSL.AutoID = field.NewInt(tableName, "auto_id")
	_sSL.ID = field.NewString(tableName, "id")
	_sSL.GatewayID = field.NewInt(tableName, "gateway_id")
	_sSL.Config = field.NewField(tableName, "config")
	_sSL.Status = field.NewString(tableName, "status")

	_sSL.fillFieldMap()

	return _sSL
}

type sSL struct {
	sSLDo sSLDo

	ALL       field.Asterisk
	Name      field.String
	Creator   field.String
	Updater   field.String
	CreatedAt field.Time
	UpdatedAt field.Time
	AutoID    field.Int
	ID        field.String
	GatewayID field.Int
	Config    field.Field
	Status    field.String

	fieldMap map[string]field.Expr
}

// Table ...
func (s sSL) Table(newTableName string) *sSL {
	s.sSLDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

// As ...
func (s sSL) As(alias string) *sSL {
	s.sSLDo.DO = *(s.sSLDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sSL) updateTableName(table string) *sSL {
	s.ALL = field.NewAsterisk(table)
	s.Name = field.NewString(table, "name")
	s.Creator = field.NewString(table, "creator")
	s.Updater = field.NewString(table, "updater")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.AutoID = field.NewInt(table, "auto_id")
	s.ID = field.NewString(table, "id")
	s.GatewayID = field.NewInt(table, "gateway_id")
	s.Config = field.NewField(table, "config")
	s.Status = field.NewString(table, "status")

	s.fillFieldMap()

	return s
}

// WithContext ...
func (s *sSL) WithContext(ctx context.Context) ISSLDo { return s.sSLDo.WithContext(ctx) }

// TableName ...
func (s sSL) TableName() string { return s.sSLDo.TableName() }

// Alias ...
func (s sSL) Alias() string { return s.sSLDo.Alias() }

// Columns ...
func (s sSL) Columns(cols ...field.Expr) gen.Columns { return s.sSLDo.Columns(cols...) }

// GetFieldByName ...
func (s *sSL) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sSL) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 10)
	s.fieldMap["name"] = s.Name
	s.fieldMap["creator"] = s.Creator
	s.fieldMap["updater"] = s.Updater
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["auto_id"] = s.AutoID
	s.fieldMap["id"] = s.ID
	s.fieldMap["gateway_id"] = s.GatewayID
	s.fieldMap["config"] = s.Config
	s.fieldMap["status"] = s.Status
}

func (s sSL) clone(db *gorm.DB) sSL {
	s.sSLDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sSL) replaceDB(db *gorm.DB) sSL {
	s.sSLDo.ReplaceDB(db)
	return s
}

type sSLDo struct{ gen.DO }

// ISSLDo ...
type ISSLDo interface {
	gen.SubQuery
	Debug() ISSLDo
	WithContext(ctx context.Context) ISSLDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISSLDo
	WriteDB() ISSLDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISSLDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISSLDo
	Not(conds ...gen.Condition) ISSLDo
	Or(conds ...gen.Condition) ISSLDo
	Select(conds ...field.Expr) ISSLDo
	Where(conds ...gen.Condition) ISSLDo
	Order(conds ...field.Expr) ISSLDo
	Distinct(cols ...field.Expr) ISSLDo
	Omit(cols ...field.Expr) ISSLDo
	Join(table schema.Tabler, on ...field.Expr) ISSLDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISSLDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISSLDo
	Group(cols ...field.Expr) ISSLDo
	Having(conds ...gen.Condition) ISSLDo
	Limit(limit int) ISSLDo
	Offset(offset int) ISSLDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISSLDo
	Unscoped() ISSLDo
	Create(values ...*model.SSL) error
	CreateInBatches(values []*model.SSL, batchSize int) error
	Save(values ...*model.SSL) error
	First() (*model.SSL, error)
	Take() (*model.SSL, error)
	Last() (*model.SSL, error)
	Find() ([]*model.SSL, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SSL, err error)
	FindInBatches(result *[]*model.SSL, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SSL) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISSLDo
	Assign(attrs ...field.AssignExpr) ISSLDo
	Joins(fields ...field.RelationField) ISSLDo
	Preload(fields ...field.RelationField) ISSLDo
	FirstOrInit() (*model.SSL, error)
	FirstOrCreate() (*model.SSL, error)
	FindByPage(offset int, limit int) (result []*model.SSL, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISSLDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

// Debug ...
func (s sSLDo) Debug() ISSLDo {
	return s.withDO(s.DO.Debug())
}

// WithContext ...
func (s sSLDo) WithContext(ctx context.Context) ISSLDo {
	return s.withDO(s.DO.WithContext(ctx))
}

// ReadDB ...
func (s sSLDo) ReadDB() ISSLDo {
	return s.Clauses(dbresolver.Read)
}

// WriteDB ...
func (s sSLDo) WriteDB() ISSLDo {
	return s.Clauses(dbresolver.Write)
}

// Session ...
func (s sSLDo) Session(config *gorm.Session) ISSLDo {
	return s.withDO(s.DO.Session(config))
}

// Clauses ...
func (s sSLDo) Clauses(conds ...clause.Expression) ISSLDo {
	return s.withDO(s.DO.Clauses(conds...))
}

// Returning ...
func (s sSLDo) Returning(value interface{}, columns ...string) ISSLDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

// Not ...
func (s sSLDo) Not(conds ...gen.Condition) ISSLDo {
	return s.withDO(s.DO.Not(conds...))
}

// Or ...
func (s sSLDo) Or(conds ...gen.Condition) ISSLDo {
	return s.withDO(s.DO.Or(conds...))
}

// Select ...
func (s sSLDo) Select(conds ...field.Expr) ISSLDo {
	return s.withDO(s.DO.Select(conds...))
}

// Where ...
func (s sSLDo) Where(conds ...gen.Condition) ISSLDo {
	return s.withDO(s.DO.Where(conds...))
}

// Order ...
func (s sSLDo) Order(conds ...field.Expr) ISSLDo {
	return s.withDO(s.DO.Order(conds...))
}

// Distinct ...
func (s sSLDo) Distinct(cols ...field.Expr) ISSLDo {
	return s.withDO(s.DO.Distinct(cols...))
}

// Omit ...
func (s sSLDo) Omit(cols ...field.Expr) ISSLDo {
	return s.withDO(s.DO.Omit(cols...))
}

// Join ...
func (s sSLDo) Join(table schema.Tabler, on ...field.Expr) ISSLDo {
	return s.withDO(s.DO.Join(table, on...))
}

// LeftJoin ...
func (s sSLDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISSLDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

// RightJoin ...
func (s sSLDo) RightJoin(table schema.Tabler, on ...field.Expr) ISSLDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

// Group ...
func (s sSLDo) Group(cols ...field.Expr) ISSLDo {
	return s.withDO(s.DO.Group(cols...))
}

// Having ...
func (s sSLDo) Having(conds ...gen.Condition) ISSLDo {
	return s.withDO(s.DO.Having(conds...))
}

// Limit ...
func (s sSLDo) Limit(limit int) ISSLDo {
	return s.withDO(s.DO.Limit(limit))
}

// Offset ...
func (s sSLDo) Offset(offset int) ISSLDo {
	return s.withDO(s.DO.Offset(offset))
}

// Scopes ...
func (s sSLDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISSLDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

// Unscoped ...
func (s sSLDo) Unscoped() ISSLDo {
	return s.withDO(s.DO.Unscoped())
}

// Create ...
func (s sSLDo) Create(values ...*model.SSL) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

// CreateInBatches ...
func (s sSLDo) CreateInBatches(values []*model.SSL, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sSLDo) Save(values ...*model.SSL) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

// First ...
func (s sSLDo) First() (*model.SSL, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SSL), nil
	}
}

// Take ...
func (s sSLDo) Take() (*model.SSL, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SSL), nil
	}
}

// Last ...
func (s sSLDo) Last() (*model.SSL, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SSL), nil
	}
}

// Find ...
func (s sSLDo) Find() ([]*model.SSL, error) {
	result, err := s.DO.Find()
	return result.([]*model.SSL), err
}

// FindInBatch ...
func (s sSLDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SSL, err error) {
	buf := make([]*model.SSL, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

// FindInBatches ...
func (s sSLDo) FindInBatches(result *[]*model.SSL, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

// Attrs ...
func (s sSLDo) Attrs(attrs ...field.AssignExpr) ISSLDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

// Assign ...
func (s sSLDo) Assign(attrs ...field.AssignExpr) ISSLDo {
	return s.withDO(s.DO.Assign(attrs...))
}

// Joins ...
func (s sSLDo) Joins(fields ...field.RelationField) ISSLDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

// Preload ...
func (s sSLDo) Preload(fields ...field.RelationField) ISSLDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

// FirstOrInit ...
func (s sSLDo) FirstOrInit() (*model.SSL, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SSL), nil
	}
}

// FirstOrCreate ...
func (s sSLDo) FirstOrCreate() (*model.SSL, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SSL), nil
	}
}

// FindByPage ...
func (s sSLDo) FindByPage(offset int, limit int) (result []*model.SSL, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

// ScanByPage ...
func (s sSLDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

// Scan ...
func (s sSLDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

// Delete ...
func (s sSLDo) Delete(models ...*model.SSL) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sSLDo) withDO(do gen.Dao) *sSLDo {
	s.DO = *do.(*gen.DO)
	return s
}
