/*
 * TencentBlueKing is pleased to support the open source community by making
 * 蓝鲸智云 - 微网关(BlueKing - Micro APIGateway) available.
 * Copyright (C) 2025 Tencent. All rights reserved.
 * Licensed under the MIT License (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 *     http://opensource.org/licenses/MIT
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * We undertake not to change the open source license (MIT license) applicable
 * to the current version of the project delivered to anyone in the future.
 */

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package repo

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/TencentBlueKing/blueking-micro-apigateway/apiserver/pkg/entity/model"
)

func newUpstream(db *gorm.DB, opts ...gen.DOOption) upstream {
	_upstream := upstream{}

	_upstream.upstreamDo.UseDB(db, opts...)
	_upstream.upstreamDo.UseModel(&model.Upstream{})

	tableName := _upstream.upstreamDo.TableName()
	_upstream.ALL = field.NewAsterisk(tableName)
	_upstream.Name = field.NewString(tableName, "name")
	_upstream.SSLID = field.NewString(tableName, "ssl_id")
	_upstream.Creator = field.NewString(tableName, "creator")
	_upstream.Updater = field.NewString(tableName, "updater")
	_upstream.CreatedAt = field.NewTime(tableName, "created_at")
	_upstream.UpdatedAt = field.NewTime(tableName, "updated_at")
	_upstream.AutoID = field.NewInt(tableName, "auto_id")
	_upstream.ID = field.NewString(tableName, "id")
	_upstream.GatewayID = field.NewInt(tableName, "gateway_id")
	_upstream.Config = field.NewField(tableName, "config")
	_upstream.Status = field.NewString(tableName, "status")

	_upstream.fillFieldMap()

	return _upstream
}

type upstream struct {
	upstreamDo upstreamDo

	ALL       field.Asterisk
	Name      field.String
	SSLID     field.String
	Creator   field.String
	Updater   field.String
	CreatedAt field.Time
	UpdatedAt field.Time
	AutoID    field.Int
	ID        field.String
	GatewayID field.Int
	Config    field.Field
	Status    field.String

	fieldMap map[string]field.Expr
}

// Table ...
func (u upstream) Table(newTableName string) *upstream {
	u.upstreamDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

// As ...
func (u upstream) As(alias string) *upstream {
	u.upstreamDo.DO = *(u.upstreamDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *upstream) updateTableName(table string) *upstream {
	u.ALL = field.NewAsterisk(table)
	u.Name = field.NewString(table, "name")
	u.SSLID = field.NewString(table, "ssl_id")
	u.Creator = field.NewString(table, "creator")
	u.Updater = field.NewString(table, "updater")
	u.CreatedAt = field.NewTime(table, "created_at")
	u.UpdatedAt = field.NewTime(table, "updated_at")
	u.AutoID = field.NewInt(table, "auto_id")
	u.ID = field.NewString(table, "id")
	u.GatewayID = field.NewInt(table, "gateway_id")
	u.Config = field.NewField(table, "config")
	u.Status = field.NewString(table, "status")

	u.fillFieldMap()

	return u
}

// WithContext ...
func (u *upstream) WithContext(ctx context.Context) IUpstreamDo { return u.upstreamDo.WithContext(ctx) }

// TableName ...
func (u upstream) TableName() string { return u.upstreamDo.TableName() }

// Alias ...
func (u upstream) Alias() string { return u.upstreamDo.Alias() }

// Columns ...
func (u upstream) Columns(cols ...field.Expr) gen.Columns { return u.upstreamDo.Columns(cols...) }

// GetFieldByName ...
func (u *upstream) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *upstream) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 11)
	u.fieldMap["name"] = u.Name
	u.fieldMap["ssl_id"] = u.SSLID
	u.fieldMap["creator"] = u.Creator
	u.fieldMap["updater"] = u.Updater
	u.fieldMap["created_at"] = u.CreatedAt
	u.fieldMap["updated_at"] = u.UpdatedAt
	u.fieldMap["auto_id"] = u.AutoID
	u.fieldMap["id"] = u.ID
	u.fieldMap["gateway_id"] = u.GatewayID
	u.fieldMap["config"] = u.Config
	u.fieldMap["status"] = u.Status
}

func (u upstream) clone(db *gorm.DB) upstream {
	u.upstreamDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u upstream) replaceDB(db *gorm.DB) upstream {
	u.upstreamDo.ReplaceDB(db)
	return u
}

type upstreamDo struct{ gen.DO }

// IUpstreamDo ...
type IUpstreamDo interface {
	gen.SubQuery
	Debug() IUpstreamDo
	WithContext(ctx context.Context) IUpstreamDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUpstreamDo
	WriteDB() IUpstreamDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUpstreamDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUpstreamDo
	Not(conds ...gen.Condition) IUpstreamDo
	Or(conds ...gen.Condition) IUpstreamDo
	Select(conds ...field.Expr) IUpstreamDo
	Where(conds ...gen.Condition) IUpstreamDo
	Order(conds ...field.Expr) IUpstreamDo
	Distinct(cols ...field.Expr) IUpstreamDo
	Omit(cols ...field.Expr) IUpstreamDo
	Join(table schema.Tabler, on ...field.Expr) IUpstreamDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUpstreamDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUpstreamDo
	Group(cols ...field.Expr) IUpstreamDo
	Having(conds ...gen.Condition) IUpstreamDo
	Limit(limit int) IUpstreamDo
	Offset(offset int) IUpstreamDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUpstreamDo
	Unscoped() IUpstreamDo
	Create(values ...*model.Upstream) error
	CreateInBatches(values []*model.Upstream, batchSize int) error
	Save(values ...*model.Upstream) error
	First() (*model.Upstream, error)
	Take() (*model.Upstream, error)
	Last() (*model.Upstream, error)
	Find() ([]*model.Upstream, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Upstream, err error)
	FindInBatches(result *[]*model.Upstream, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Upstream) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUpstreamDo
	Assign(attrs ...field.AssignExpr) IUpstreamDo
	Joins(fields ...field.RelationField) IUpstreamDo
	Preload(fields ...field.RelationField) IUpstreamDo
	FirstOrInit() (*model.Upstream, error)
	FirstOrCreate() (*model.Upstream, error)
	FindByPage(offset int, limit int) (result []*model.Upstream, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUpstreamDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

// Debug ...
func (u upstreamDo) Debug() IUpstreamDo {
	return u.withDO(u.DO.Debug())
}

// WithContext ...
func (u upstreamDo) WithContext(ctx context.Context) IUpstreamDo {
	return u.withDO(u.DO.WithContext(ctx))
}

// ReadDB ...
func (u upstreamDo) ReadDB() IUpstreamDo {
	return u.Clauses(dbresolver.Read)
}

// WriteDB ...
func (u upstreamDo) WriteDB() IUpstreamDo {
	return u.Clauses(dbresolver.Write)
}

// Session ...
func (u upstreamDo) Session(config *gorm.Session) IUpstreamDo {
	return u.withDO(u.DO.Session(config))
}

// Clauses ...
func (u upstreamDo) Clauses(conds ...clause.Expression) IUpstreamDo {
	return u.withDO(u.DO.Clauses(conds...))
}

// Returning ...
func (u upstreamDo) Returning(value interface{}, columns ...string) IUpstreamDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

// Not ...
func (u upstreamDo) Not(conds ...gen.Condition) IUpstreamDo {
	return u.withDO(u.DO.Not(conds...))
}

// Or ...
func (u upstreamDo) Or(conds ...gen.Condition) IUpstreamDo {
	return u.withDO(u.DO.Or(conds...))
}

// Select ...
func (u upstreamDo) Select(conds ...field.Expr) IUpstreamDo {
	return u.withDO(u.DO.Select(conds...))
}

// Where ...
func (u upstreamDo) Where(conds ...gen.Condition) IUpstreamDo {
	return u.withDO(u.DO.Where(conds...))
}

// Order ...
func (u upstreamDo) Order(conds ...field.Expr) IUpstreamDo {
	return u.withDO(u.DO.Order(conds...))
}

// Distinct ...
func (u upstreamDo) Distinct(cols ...field.Expr) IUpstreamDo {
	return u.withDO(u.DO.Distinct(cols...))
}

// Omit ...
func (u upstreamDo) Omit(cols ...field.Expr) IUpstreamDo {
	return u.withDO(u.DO.Omit(cols...))
}

// Join ...
func (u upstreamDo) Join(table schema.Tabler, on ...field.Expr) IUpstreamDo {
	return u.withDO(u.DO.Join(table, on...))
}

// LeftJoin ...
func (u upstreamDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUpstreamDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

// RightJoin ...
func (u upstreamDo) RightJoin(table schema.Tabler, on ...field.Expr) IUpstreamDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

// Group ...
func (u upstreamDo) Group(cols ...field.Expr) IUpstreamDo {
	return u.withDO(u.DO.Group(cols...))
}

// Having ...
func (u upstreamDo) Having(conds ...gen.Condition) IUpstreamDo {
	return u.withDO(u.DO.Having(conds...))
}

// Limit ...
func (u upstreamDo) Limit(limit int) IUpstreamDo {
	return u.withDO(u.DO.Limit(limit))
}

// Offset ...
func (u upstreamDo) Offset(offset int) IUpstreamDo {
	return u.withDO(u.DO.Offset(offset))
}

// Scopes ...
func (u upstreamDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUpstreamDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

// Unscoped ...
func (u upstreamDo) Unscoped() IUpstreamDo {
	return u.withDO(u.DO.Unscoped())
}

// Create ...
func (u upstreamDo) Create(values ...*model.Upstream) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

// CreateInBatches ...
func (u upstreamDo) CreateInBatches(values []*model.Upstream, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u upstreamDo) Save(values ...*model.Upstream) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

// First ...
func (u upstreamDo) First() (*model.Upstream, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Upstream), nil
	}
}

// Take ...
func (u upstreamDo) Take() (*model.Upstream, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Upstream), nil
	}
}

// Last ...
func (u upstreamDo) Last() (*model.Upstream, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Upstream), nil
	}
}

// Find ...
func (u upstreamDo) Find() ([]*model.Upstream, error) {
	result, err := u.DO.Find()
	return result.([]*model.Upstream), err
}

// FindInBatch ...
func (u upstreamDo) FindInBatch(
	batchSize int,
	fc func(tx gen.Dao, batch int) error,
) (results []*model.Upstream, err error) {
	buf := make([]*model.Upstream, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

// FindInBatches ...
func (u upstreamDo) FindInBatches(
	result *[]*model.Upstream,
	batchSize int,
	fc func(tx gen.Dao, batch int) error,
) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

// Attrs ...
func (u upstreamDo) Attrs(attrs ...field.AssignExpr) IUpstreamDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

// Assign ...
func (u upstreamDo) Assign(attrs ...field.AssignExpr) IUpstreamDo {
	return u.withDO(u.DO.Assign(attrs...))
}

// Joins ...
func (u upstreamDo) Joins(fields ...field.RelationField) IUpstreamDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

// Preload ...
func (u upstreamDo) Preload(fields ...field.RelationField) IUpstreamDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

// FirstOrInit ...
func (u upstreamDo) FirstOrInit() (*model.Upstream, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Upstream), nil
	}
}

// FirstOrCreate ...
func (u upstreamDo) FirstOrCreate() (*model.Upstream, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Upstream), nil
	}
}

// FindByPage ...
func (u upstreamDo) FindByPage(offset int, limit int) (result []*model.Upstream, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

// ScanByPage ...
func (u upstreamDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

// Scan ...
func (u upstreamDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

// Delete ...
func (u upstreamDo) Delete(models ...*model.Upstream) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *upstreamDo) withDO(do gen.Dao) *upstreamDo {
	u.DO = *do.(*gen.DO)
	return u
}
